### ISSUE TITLE
localMedia: true - not working inside repeater fields

### ISSUE THREAD

**Issue by mr-toast** [cosmicjs/gatsby-source-cosmicjs#23]
Image fields inside repeater fields don't have their local data added to GraphQL making images in repeaters not usable by gatsby-image 

![CleanShot 2021-01-04 at 17 42 55](https://user-images.githubusercontent.com/7333784/103528140-05028e00-4eb6-11eb-8436-f9105013f135.png)

**Comment by raae** [comment]
Is it working at all? The creation of local file nodes are happening inside a resolver and can thus result in erratic behaviour [since v4](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#2-data-mutations-need-to-happen-during-sourcenodes-or-oncreatenode). You might get success by setting `localMedia` to `false` and using [gatsby-plugin-remote-images](https://github.com/graysonhicks/gatsby-plugin-remote-images) instead.

**Comment by AndreasEracleous** [comment]
> Is it working at all? The creation of local file nodes are happening inside a resolver and can thus result in erratic behaviour [since v4](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#2-data-mutations-need-to-happen-during-sourcenodes-or-oncreatenode). You might get success by setting `localMedia` to `false` and using [gatsby-plugin-remote-images](https://github.com/graysonhicks/gatsby-plugin-remote-images) instead.

@raae thanks for the solution. It works! I set `localMedia` to `false` and using [gatsby-plugin-remote-images](https://github.com/graysonhicks/gatsby-plugin-remote-images)

Then in **gatsby-config.js**, I added the following configuration.
`  plugins: [ 
    {
      resolve: 'gatsby-source-cosmicjs',
      options: {
        bucketSlug: process.env.COSMIC_BUCKET,
        objectTypes: ['posts', 'settings'],
        apiAccess: {
          read_key: process.env.COSMIC_READ_KEY,
        },
        localMedia: false,
      },
    },
   **{
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'CosmicjsPosts',
        imagePath: 'metadata.hero.url',
      },
    },
    {
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'CosmicjsSettings',
        imagePath: 'metadata.homepage_hero.url',
      },**
    },]`

**http://localhost:8000/___graphql**

<img width="301" alt="Gatsby - GraphiQL 2022-07-17 23-37-10" src="https://user-images.githubusercontent.com/3426364/179424065-4cdc2daa-6c75-4503-b523-1a2c3aac3b8e.png">

**Comment by Nosferatu31** [comment]
@raae @AndreasEracleous 

Regarding this, how could I have a proper `localImage` in this case?

```
query LandingPageBySlug($slug: String!) {
    cosmicjsLandingPages(slug: { eq: $slug }) {
      metadata {
        blocks {
          ...
          localImage {
            childImageSharp {
              gatsbyImageData(height: 700)
              original {
                width
                height
              }
            }
          }
          metadata {
            ...
            image {
              url
            }
            ...
          }
        }
      }
    }
  }
  ```
  
  In `gatsby-config` I've set this up, but `localImage` always returns `null`:
  
  ```
{
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'CosmicjsLandingPagesMetadataBlocks',
        imagePath: 'metadata.image.url',
      },
}
  ```
