### ISSUE TITLE
Upgrade from 0.0.6 to 1.0.0 breaks Gatsby build

### ISSUE THREAD

**Issue by tekhaus** [cosmicjs/gatsby-source-cosmicjs#9]
⠋ Add inferred types

 ERROR 

Syntax Error: Unexpected Name "CosmicjsBasic"

  GraphQLError: Syntax Error: Unexpected Name "CosmicjsBasic"

==============
The underlying object type is "Basic Pages" with a slug of **basic-pages**. Removing this object type let's the build complete. All other object types are single words with no hyphens, so I'm guessing the @1.0.0 update is erroneously trimming the slug from the dash onward.

**Comment by tonyspiro** [comment]
Thank @tekhaus, we're looking into this now.

**Comment by tonyspiro** [comment]
Hey @tekhaus, this should now be fixed in the latest version [v1.0.2](https://www.npmjs.com/package/gatsby-source-cosmicjs)

**Comment by tekhaus** [comment]
Tested, and I had to lowercase the word after the hyphen (allCosmicjsBasicPages => allCosmicjsBasicpages) for this update to work, which is fine if that's intended.

Thanks for the quick fix!

**Comment by tonyspiro** [comment]
You're right, this was messing up the camelCase, this is now fixed in [v1.0.3](https://www.npmjs.com/package/gatsby-source-cosmicjs) Can you please confirm @tekhaus?

**Comment by tekhaus** [comment]
Looks good!
